export { PhaserEditorPlugin } from './PhaserEditorPlugin';
export { EditorScene } from './EditorScene';
export { EditorState, EditorTool } from './core/EditorState';
export { CoordinateSystem } from './core/CoordinateSystem';
export { SelectionManager } from './core/SelectionManager';
export { GizmoManager } from './gizmos/GizmoManager';
export { MoveGizmo, DragHandle } from './gizmos/MoveGizmo';
export { RotateGizmo, RotateHandle } from './gizmos/RotateGizmo';
export { ScaleGizmo, ScaleHandle } from './gizmos/ScaleGizmo';
export { HitAreaGizmo, HitAreaHandle } from './gizmos/HitAreaGizmo';
export { EditorUI } from './ui/EditorUI';
export { InspectorPanel } from './ui/InspectorPanel';
export { HierarchyPanel } from './ui/HierarchyPanel';
export { ToolbarPanel } from './ui/ToolbarPanel';
export { SnappingEngine } from './core/SnappingEngine';
export { EditorFrame } from './ui/EditorFrame';

export type { EditorPluginConfig, ChangeDiff } from './PhaserEditorPlugin';
export type { EditorUISlots } from './ui/EditorUI';
export type { SnappingConfig } from './core/EditorState';
export type { SnapGuide } from './core/SnappingEngine';
